#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""
Name: launcher.py
Porpose: main launch script of ffcuesplitter_gui
Compatibility: Python3
Author: Gianluca Pernigotto <jeanlucperni@gmail.com>
Copyright: (c) 2022 Gianluca Pernigotto <jeanlucperni@gmail.com>
license: GPL3
Rev: Jan.26.2022
Code checker: flake8, pylint
########################################################

This file is part of Cuesplitter-GUI.

   Cuesplitter-GUI is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Cuesplitter-GUI is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Cuesplitter-GUI.  If not, see <http://www.gnu.org/licenses/>.
"""


if __name__ == '__main__':
    from ffcuesplitter_gui import gui_app
    gui_app.main()
